"""Edited Concerts Table

Revision ID: ae5ccf64bfd0
Revises: a4f06da5a823
Create Date: 2024-09-17 00:59:19.832344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae5ccf64bfd0'
down_revision = 'a4f06da5a823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
